name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate wrapper jar
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Get version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV
      - name: Rename APK with version
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-$VERSION.apk
      - name: Run unit tests
        if: github.event_name == 'push'
        run: ./gradlew test
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug-$VERSION.apk
      - name: Send APK to Telegram
        if: github.event_name == 'push'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          CHANGELOG=$(grep '^-' HISTORY.md | tail -n 1 | sed 's/^-[ ]*//')
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument \
            -F chat_id=${TELEGRAM_CHAT_ID} \
            -F document=@app/build/outputs/apk/debug/app-debug-$VERSION.apk \
            -F caption="$CHANGELOG"

